chime: Drop DTC_EXT flags
 * Causing a fatal error
   FATAL ERROR: Unrecognized check name "interrupt_provider"
   make[4]: *** [scripts/Makefile.lib:319: arch/arm64/boot/dts/vendor/qcom/bengal.dtb] Error 1

Signed-off-by: frost. (frostg-012) <frost@nusantararom.org>
Change-Id: I9fde49cd2183181814300d4cce93a40cf147c643
Signed-off-by: Vayruz Rafli <vayruzrafli79@outlook.co.id>